AWSTemplateFormatVersion: 2010-09-09
Description: sample of cloudformation template for deploying a lambda function form S3.
Resources:
  Ruru8:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: ruru8
        S3Key: lambda_function.rb.zip
      Description: deploy lambda template
      FunctionName: ruru8_lambda_practice
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::945695219709:role/portfolio-refrection-questionnaire-lambda-role
      Runtime: ruby2.5
